Add a parameter to specify the DB host #18

diff --git a/civihr-install b/civihr-install
--- a/civihr-install
+++ b/civihr-install
@@ -138,6 +138,7 @@ Required parameters:
 
 Optional parameters:
   --dbpass [mysql-password]     Password for mysql
+  --dbhost [mysql-host]         host for mysql
   --webroot [root dir path]     The full path to the website root. If not given, the site will be installed in the current directory
   --force-drop                  Drop existing databases for --crmdb and --cmsdb options.
 EOT
@@ -292,10 +293,10 @@ function _database_install_cms() {
   civihr_assert_vars _database_install_cms CMS_ROOT SITE_NAME SITE_ID TMPDIR
   # Force drop database.
   if [ "$FORCE_DROP" ]; then
-      mysql -u$DB_USER $PASS_PARAM -e "drop database $CMSdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
+      mysql -u$DB_USER $PASS_PARAM -h $CMS_DB_HOST -e "drop database $CMSdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
   fi
   # Create database.
-  mysql -u$DB_USER $PASS_PARAM -e "create database $CMSdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
+  #mysql -u$DB_USER $PASS_PARAM -h $CMS_DB_HOST -e "create database $CMSdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
   # Assign values to global variables.
   [ -z "$CMS_DB_USER" ]           && CMS_DB_USER="$DB_USER"
   [ -z "$CMS_DB_PASS" ]           && CMS_DB_PASS="$DB_PASS"
@@ -320,10 +321,10 @@ function _database_install_civi() {
   civihr_assert_vars _database_install_civi CMS_ROOT SITE_NAME SITE_ID TMPDIR
   # Force drop database.
   if [ "$FORCE_DROP" ]; then
-      mysql -u$DB_USER $PASS_PARAM -e "drop database $CIVIdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
+      mysql -u$DB_USER $PASS_PARAM -h $CMS_DB_HOST -e "drop database $CIVIdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
   fi
   # Create database.
-  mysql -u$DB_USER $PASS_PARAM -e "create database $CIVIdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
+  #mysql -u$DB_USER $PASS_PARAM -h $CIVI_DB_HOST -e "create database $CIVIdbName" || { echo "[[Please fix above MySQL error.]]"; exit 1;  }
   # Assign values to global variables.
   [ -z "$CIVI_DB_USER" ]           && CIVI_DB_USER="$DB_USER"
   [ -z "$CIVI_DB_PASS" ]           && CIVI_DB_PASS="$DB_PASS"
@@ -628,6 +629,18 @@ function civihr_parse_options() {
           DB_PASS="$1"
         fi
         [ -n "$DB_PASS" ] && PASS_PARAM="-p$DB_PASS"
+        shift
+        ;;
+
+      --dbhost)
+        if [ -z "$1" ]; then
+          echo -n "Enter Password for Mysql:"
+          read -s DB_HOST
+          echo
+        else
+          CMS_DB_HOST="$1"
+          CIVI_DB_HOST="$1"
+        fi
         shift
         ;;
 
